name: .NET Core

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.405
      - name: Install dependencies
        run: dotnet restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Test Mutator
        run: |
          dotnet tool install --tool-path ./tools dotnet-stryker \
          && cd ./tests/LucasRosinelli.Pipeline.Api.Tests/ \
          && ../../tools/dotnet-stryker --config-file-path ../stryker-config.json
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Quality
        uses: Secbyte/dotnet-sonarscanner@v2.3
        with:
          buildCommand: dotnet build .
          projectKey: LucasRosinelli_cicd-pipeline-poc
          projectName: cicd-pipeline-poc
          sonarOrganisation: lucasrosinelli
          sonarHostname: https://sonarcloud.io
          beginArguments: >
            /d:sonar.verbose="true"
            /d:sonar.cs.opencover.reportsPaths='"/coverage.xml"'
            /d:sonar.coverage.exclusions='"tests/**","**/*.cs","**/*.md"'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
